version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "00:00"
    commit-message:
      prefix: "ci:"
    cooldown:
      default-days: 7

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      time: "00:00"
    commit-message:
      prefix: "go:"
    cooldown:
      default-days: 7